/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalExam;

import TK4_02.NO_02;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class NO_5 extends javax.swing.JFrame {

    /**
     * Creates new form NO_5
     */
    public NO_5() {
        initComponents();
        viewMenuCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lblToko = new javax.swing.JLabel();
        lblToko1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtViewNamaCustomer = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtViewNamaWaitress = new javax.swing.JTextPane();
        txtOrder = new java.awt.TextField();
        txtCustomer = new java.awt.TextField();
        txtWaitress = new java.awt.TextField();
        btnViewNamaWaitress = new javax.swing.JButton();
        lblIDOrder = new javax.swing.JLabel();
        lvlKdWaitress = new javax.swing.JLabel();
        lblKdCustomer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnViewNamaCustomer = new javax.swing.JButton();
        txtGrandTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblKdMenu = new javax.swing.JLabel();
        cmbKdMenu = new java.awt.Choice();
        jLabel7 = new javax.swing.JLabel();
        lblNamaMenu = new javax.swing.JLabel();
        txtNamaMenu = new java.awt.TextField();
        lblJumlah = new javax.swing.JLabel();
        txtJumlah = new java.awt.TextField();
        lblHarga = new javax.swing.JLabel();
        txtHarga = new java.awt.TextField();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetailOrder = new javax.swing.JTable();
        lblDetailOrder = new javax.swing.JLabel();
        lblBayar = new javax.swing.JLabel();
        lblKembalian = new javax.swing.JLabel();
        txtBayar = new java.awt.TextField();
        txtKembalian = new java.awt.TextField();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane3.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblToko.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblToko.setText("Cafe ENAK");

        lblToko1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblToko1.setText("ORDER");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        txtViewNamaCustomer.setBackground(new java.awt.Color(255, 153, 102));
        jScrollPane4.setViewportView(txtViewNamaCustomer);

        txtViewNamaWaitress.setBackground(new java.awt.Color(255, 153, 102));
        jScrollPane5.setViewportView(txtViewNamaWaitress);

        txtOrder.setBackground(new java.awt.Color(255, 153, 102));
        txtOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderActionPerformed(evt);
            }
        });

        txtCustomer.setBackground(new java.awt.Color(255, 153, 102));

        txtWaitress.setBackground(new java.awt.Color(255, 153, 102));

        btnViewNamaWaitress.setBackground(new java.awt.Color(102, 153, 255));
        btnViewNamaWaitress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnViewNamaWaitress.setForeground(new java.awt.Color(0, 0, 0));
        btnViewNamaWaitress.setText("View");
        btnViewNamaWaitress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNamaWaitressActionPerformed(evt);
            }
        });

        lblIDOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIDOrder.setForeground(new java.awt.Color(0, 0, 0));
        lblIDOrder.setText("ID Order");

        lvlKdWaitress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lvlKdWaitress.setForeground(new java.awt.Color(0, 0, 0));
        lvlKdWaitress.setText("Kode Waitress");

        lblKdCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKdCustomer.setForeground(new java.awt.Color(0, 0, 0));
        lblKdCustomer.setText("Kode Customer");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText(":");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText(":");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(":");

        btnViewNamaCustomer.setBackground(new java.awt.Color(102, 153, 255));
        btnViewNamaCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnViewNamaCustomer.setForeground(new java.awt.Color(0, 0, 0));
        btnViewNamaCustomer.setText("View");
        btnViewNamaCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNamaCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblKdCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIDOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnViewNamaWaitress)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnViewNamaCustomer)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lvlKdWaitress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWaitress, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lvlKdWaitress)
                                .addComponent(jLabel6))
                            .addComponent(txtWaitress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIDOrder)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKdCustomer)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane4)
                                .addComponent(btnViewNamaCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewNamaWaitress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );

        txtGrandTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        lblKdMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKdMenu.setForeground(new java.awt.Color(0, 0, 0));
        lblKdMenu.setText("Kode Menu");

        cmbKdMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKdMenuItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(":");

        lblNamaMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNamaMenu.setForeground(new java.awt.Color(0, 0, 0));
        lblNamaMenu.setText("Nama Menu");

        txtNamaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMenuActionPerformed(evt);
            }
        });

        lblJumlah.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJumlah.setForeground(new java.awt.Color(0, 0, 0));
        lblJumlah.setText("Jumlah");

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        txtJumlah.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtJumlahPropertyChange(evt);
            }
        });
        txtJumlah.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtJumlahTextValueChanged(evt);
            }
        });

        lblHarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(0, 0, 0));
        lblHarga.setText("Harga");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        btnTambah.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTambah.setText("Tambah Item");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHapus.setText("Hapus Item");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblKdMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbKdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblJumlah)
                        .addGap(56, 56, 56)
                        .addComponent(lblHarga)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblKdMenu)
                                .addComponent(lblNamaMenu))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbKdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJumlah)
                            .addComponent(lblHarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTambah)
                                .addComponent(btnHapus)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        tblDetailOrder.setBackground(new java.awt.Color(204, 204, 204));
        tblDetailOrder.setForeground(new java.awt.Color(0, 0, 0));
        tblDetailOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Menu", "Nama Menu", "Jumlah", "Harga"
            }
        ));
        tblDetailOrder.setGridColor(new java.awt.Color(0, 0, 0));
        tblDetailOrder.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tblDetailOrder);

        lblDetailOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDetailOrder.setForeground(new java.awt.Color(0, 0, 0));
        lblDetailOrder.setText("DETAIL ORDER");

        lblBayar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBayar.setForeground(new java.awt.Color(0, 0, 0));
        lblBayar.setText("Bayar");

        lblKembalian.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKembalian.setForeground(new java.awt.Color(0, 0, 0));
        lblKembalian.setText("Kembalian");

        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });

        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKembalian)
                    .addComponent(lblBayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDetailOrder))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetailOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBayar)
                            .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSimpan))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKembalian)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeluar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblToko)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblToko1)
                        .addGap(299, 299, 299))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblToko)
                .addGap(3, 3, 3)
                .addComponent(lblToko1)
                .addGap(8, 8, 8)
                .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewNamaCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNamaCustomerActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:4000/enak","root","");  

            String kdCustomer = txtCustomer.getText();
            Statement stm = con.createStatement();
            String sql = "select * from customer where kd_customer='" + kdCustomer + "'";
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next()) {
                txtViewNamaCustomer.setText(rs.getString("nm_customer"));
            } else {
                JOptionPane.showMessageDialog(rootPane, "kode customer belum terdaftar");
            }
        } catch (SQLException e){
            System.out.println(e);
            throw new IllegalStateException(e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NO_02.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewNamaCustomerActionPerformed

    private void btnViewNamaWaitressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNamaWaitressActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:4000/enak","root","");  

            String kdWaitress = txtWaitress.getText();
            Statement stm = con.createStatement();
            String sql = "select * from waitress where kd_waitress='" + kdWaitress + "'";
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next()) {
                txtViewNamaWaitress.setText(rs.getString("nm_waitress"));
            } else {
                JOptionPane.showMessageDialog(rootPane, "kode waitress belum terdaftar");
            }
        } catch (SQLException e){
            System.out.println(e);
            throw new IllegalStateException(e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NO_02.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewNamaWaitressActionPerformed

    private void viewMenuCombo() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:4000/enak","root","");  

            Statement stm = con.createStatement();
            String sql = "select * from menu";
            ResultSet rs = stm.executeQuery(sql);
            cmbKdMenu.addItem("");
            while(rs.next()) {
                cmbKdMenu.addItem(rs.getString("kd_menu"));
            }
        } catch (SQLException e){
            System.out.println(e);
            throw new IllegalStateException(e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NO_02.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void txtNamaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMenuActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    int grandTotal = 0;
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String data[] = {cmbKdMenu.getSelectedItem(),txtNamaMenu.getText(),txtJumlah.getText(),txtHarga.getText()};
        
        int total = Integer.parseInt(txtHarga.getText());
        grandTotal += total;
        DefaultTableModel tblModel = (DefaultTableModel)tblDetailOrder.getModel();
        
        tblModel.addRow(data);
        
        txtGrandTotal.setText(Integer.toString(grandTotal));
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        txtNamaMenu.setText("");
        txtJumlah.setText("");
        txtHarga.setText("");
        cmbKdMenu.removeAll();
        
        viewMenuCombo();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:4000/enak","root","");  

            String kodeMenu = "";
            int jumlah = 0;
            int harga = 0;
            for (int i = 0; i < tblDetailOrder.getRowCount(); i++) {
                kodeMenu = tblDetailOrder.getValueAt(i, 0).toString();
                jumlah = Integer.parseInt(tblDetailOrder.getValueAt(i, 2).toString());
                harga = Integer.parseInt(tblDetailOrder.getValueAt(i, 3).toString());
                
                String query = "insert into `order` (kd_order, kd_customer, kd_waitress, kd_menu, qty_menu, harga)"
                + " values (?, ?, ?, ?, ?, ?)";
            
                PreparedStatement preparedStmt = con.prepareStatement(query);
                preparedStmt.setString(1, txtOrder.getText());
                preparedStmt.setString(2, txtCustomer.getText());
                preparedStmt.setString(3, txtWaitress.getText());
                preparedStmt.setString(4, kodeMenu);
                preparedStmt.setInt(5, jumlah);
                preparedStmt.setInt (6, harga);

                preparedStmt.execute();
            }
        } catch (SQLException e){
            System.out.println(e);
            throw new IllegalStateException(e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NO_02.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        int bayar = Integer.parseInt(txtBayar.getText());
        
        int kembalian = bayar - grandTotal;
        if (kembalian < 0) {
            JOptionPane.showMessageDialog(rootPane, "kurang bayar!!!!!");
        } else {
            txtKembalian.setText(Integer.toString(kembalian));
        }
    }//GEN-LAST:event_txtBayarActionPerformed

    private void cmbKdMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKdMenuItemStateChanged
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:4000/enak","root","");  

            Statement stm = con.createStatement();
            String sql = "select * from menu where kd_menu='" + cmbKdMenu.getSelectedItem() + "'";
            ResultSet rs = stm.executeQuery(sql);
            if (rs.next()) {
                txtNamaMenu.setText(rs.getString("nm_menu"));
            }
        } catch (SQLException e){
            System.out.println(e);
            throw new IllegalStateException(e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NO_02.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbKdMenuItemStateChanged

    private void txtJumlahPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtJumlahPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahPropertyChange

    private void txtJumlahTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtJumlahTextValueChanged
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:4000/enak","root","");  

            Statement stm = con.createStatement();
            String sql = "select * from menu where kd_menu='" + cmbKdMenu.getSelectedItem() + "'";
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()) {
                int jumlah = Integer.parseInt(txtJumlah.getText());
                int hargaMenu = Integer.parseInt(rs.getString("harga"));
                int total = jumlah * hargaMenu;
                txtHarga.setText(Integer.toString(total));
            }
        } catch (SQLException e){
            System.out.println(e);
            throw new IllegalStateException(e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NO_02.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtJumlahTextValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NO_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NO_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NO_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NO_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NO_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnViewNamaCustomer;
    private javax.swing.JButton btnViewNamaWaitress;
    private java.awt.Choice cmbKdMenu;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblBayar;
    private javax.swing.JLabel lblDetailOrder;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIDOrder;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKdCustomer;
    private javax.swing.JLabel lblKdMenu;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblNamaMenu;
    private javax.swing.JLabel lblToko;
    private javax.swing.JLabel lblToko1;
    private javax.swing.JLabel lvlKdWaitress;
    private javax.swing.JTable tblDetailOrder;
    private java.awt.TextField txtBayar;
    private java.awt.TextField txtCustomer;
    private javax.swing.JTextField txtGrandTotal;
    private java.awt.TextField txtHarga;
    private java.awt.TextField txtJumlah;
    private java.awt.TextField txtKembalian;
    private java.awt.TextField txtNamaMenu;
    private java.awt.TextField txtOrder;
    private javax.swing.JTextPane txtViewNamaCustomer;
    private javax.swing.JTextPane txtViewNamaWaitress;
    private java.awt.TextField txtWaitress;
    // End of variables declaration//GEN-END:variables
}
